// Tsongra — Ladakh crop, seed and place catalogue.
// Local names are the common Ladakhi/Balti transliterations used in the market.
// Sowing windows are given per altitude zone (see ZONES) and are guidance, not gospel:
// every valley runs a week or two off its neighbour.

// ---------------------------------------------------------------------------
// Altitude zones. Everything in the seed bank is scheduled against these.
// ---------------------------------------------------------------------------
export const ZONES = [
  {
    key: 'low',
    label: 'Low valleys',
    local: 'Yog-sa',
    alt: '2,600 – 3,200 m',
    example: 'Turtuk, Dah-Hanu, Khaltse, Kargil town, Sanjak',
    season: 'Late March → October',
    note: 'The longest season in Ladakh. Apricot, walnut, grape and even melon ripen here.',
  },
  {
    key: 'mid',
    label: 'Leh belt',
    local: 'Bar-sa',
    alt: '3,200 – 3,600 m',
    example: 'Leh, Choglamsar, Saspol, Diskit, Sankoo, Shey',
    season: 'April → early October',
    note: 'The main farming belt. One field crop a year outdoors, three cycles under a greenhouse.',
  },
  {
    key: 'high',
    label: 'High plateau',
    local: 'Tho-sa',
    alt: '3,600 – 4,300 m',
    example: 'Padum, Durbuk, Nyoma, Korzok, upper Drass',
    season: 'Mid-May → September',
    note: 'A short, sharp season. Barley, peas, turnip and fodder are the safe bets.',
  },
  {
    key: 'gh',
    label: 'Greenhouse / trench',
    local: 'Chhu-khang',
    alt: 'Any altitude',
    example: 'Trench greenhouse, passive solar greenhouse, low tunnel',
    season: 'All year',
    note: 'A trench greenhouse stays roughly 20°C warmer by day. Greens right through the winter.',
  },
];

// ---------------------------------------------------------------------------
// Marketplace categories
// ---------------------------------------------------------------------------
export const CATEGORIES = [
  { key: 'veg', label: 'Vegetables', local: 'Tsod-ma', icon: '🥬', color: '#4C7A34' },
  { key: 'fruit', label: 'Fruit & Nuts', local: 'Shing-tog', icon: '🍑', color: '#E07A2F' },
  { key: 'grain', label: 'Grain & Flour', local: 'Dru-rigs', icon: '🌾', color: '#C79A2B' },
  { key: 'seed', label: 'Seeds & Saplings', local: 'Sa-bön', icon: '🌱', color: '#2E8B57' },
  { key: 'dairy', label: 'Dairy & Butter', local: 'Mar-cha', icon: '🧈', color: '#1E7E8C' },
  { key: 'dry', label: 'Dried & Preserved', local: 'Kam-po', icon: '🫙', color: '#7E2B2B' },
  { key: 'other', label: 'Other local goods', local: 'Zhan-dag', icon: '🧺', color: '#6B5B4A' },
];

export const UNITS = [
  { key: 'kg', label: 'per kg' },
  { key: 'quintal', label: 'per quintal (100 kg)' },
  { key: 'bag', label: 'per bag' },
  { key: 'bundle', label: 'per bundle' },
  { key: 'dozen', label: 'per dozen' },
  { key: 'piece', label: 'per piece' },
  { key: 'litre', label: 'per litre' },
  { key: 'packet', label: 'per seed packet' },
  { key: 'sapling', label: 'per sapling' },
];

// ---------------------------------------------------------------------------
// Crops you can list for sale. `local` is the Ladakhi / Balti market name.
// ---------------------------------------------------------------------------
export const CROPS = [
  // --- Vegetables -----------------------------------------------------------
  { key: 'turnip', cat: 'veg', name: 'Turnip', local: 'Nyungma', icon: '🥬', season: 'Aug–Nov' },
  { key: 'radish', cat: 'veg', name: 'Radish', local: 'Labuk', icon: '🥕', season: 'Jul–Oct' },
  { key: 'potato', cat: 'veg', name: 'Potato', local: 'Aalu', icon: '🥔', season: 'Aug–Oct' },
  { key: 'cabbage', cat: 'veg', name: 'Cabbage', local: 'Band gobi', icon: '🥬', season: 'Jul–Oct' },
  { key: 'cauliflower', cat: 'veg', name: 'Cauliflower', local: 'Phool gobi', icon: '🥦', season: 'Aug–Oct' },
  { key: 'kohlrabi', cat: 'veg', name: 'Kohlrabi', local: 'Ganth gobi', icon: '🥬', season: 'Jul–Sep' },
  { key: 'spinach', cat: 'veg', name: 'Spinach', local: 'Palak', icon: '🥬', season: 'All year (greenhouse)' },
  { key: 'chard', cat: 'veg', name: 'Swiss chard', local: 'Chard palak', icon: '🥬', season: 'All year (greenhouse)' },
  { key: 'kale', cat: 'veg', name: 'Kale', local: 'Kale', icon: '🥬', season: 'Oct–Mar (greenhouse)' },
  { key: 'pakchoi', cat: 'veg', name: 'Pak choi', local: 'Pak choi', icon: '🥬', season: 'Oct–Mar (greenhouse)' },
  { key: 'lettuce', cat: 'veg', name: 'Lettuce / salad', local: 'Salad', icon: '🥗', season: 'May–Sep' },
  { key: 'coriander', cat: 'veg', name: 'Coriander', local: 'Dhaniya', icon: '🌿', season: 'All year' },
  { key: 'onion', cat: 'veg', name: 'Onion', local: 'Tsong', icon: '🧅', season: 'Aug–Oct' },
  { key: 'garlic', cat: 'veg', name: 'Garlic', local: 'Gogpa', icon: '🧄', season: 'Aug–Sep' },
  { key: 'carrot', cat: 'veg', name: 'Carrot', local: 'Gajar', icon: '🥕', season: 'Aug–Oct' },
  { key: 'beetroot', cat: 'veg', name: 'Beetroot', local: 'Chukandar', icon: '🫐', season: 'Aug–Oct' },
  { key: 'peas_green', cat: 'veg', name: 'Green peas', local: 'Sran-ma', icon: '🫛', season: 'Jul–Sep' },
  { key: 'broadbean', cat: 'veg', name: 'Broad bean', local: 'Bakla', icon: '🫘', season: 'Aug–Sep' },
  { key: 'pumpkin', cat: 'veg', name: 'Pumpkin', local: 'Kaddu', icon: '🎃', season: 'Aug–Oct' },
  { key: 'tomato', cat: 'veg', name: 'Tomato', local: 'Tamatar', icon: '🍅', season: 'Jun–Sep (greenhouse)' },
  { key: 'cucumber', cat: 'veg', name: 'Cucumber', local: 'Kheera', icon: '🥒', season: 'Jun–Sep (greenhouse)' },
  { key: 'capsicum', cat: 'veg', name: 'Capsicum', local: 'Shimla mirch', icon: '🫑', season: 'Jul–Sep (greenhouse)' },
  { key: 'broccoli', cat: 'veg', name: 'Broccoli', local: 'Broccoli', icon: '🥦', season: 'Aug–Oct' },
  { key: 'mint', cat: 'veg', name: 'Mint / herbs', local: 'Pudina', icon: '🌿', season: 'Jun–Sep' },

  // --- Fruit & nuts ---------------------------------------------------------
  { key: 'apricot', cat: 'fruit', name: 'Fresh apricot', local: 'Chuli', icon: '🍑', season: 'Jul–Aug' },
  { key: 'apricot_rk', cat: 'fruit', name: 'Raktsey Karpo apricot (GI)', local: 'Raktsey Karpo', icon: '🍑', season: 'Jul–Aug' },
  { key: 'apple', cat: 'fruit', name: 'Apple', local: 'Kushu', icon: '🍎', season: 'Aug–Oct' },
  { key: 'walnut', cat: 'fruit', name: 'Walnut', local: 'Starga', icon: '🌰', season: 'Sep–Oct' },
  { key: 'almond', cat: 'fruit', name: 'Almond', local: 'Badam', icon: '🌰', season: 'Aug–Sep' },
  { key: 'seabuckthorn', cat: 'fruit', name: 'Sea buckthorn berry', local: 'Tsestalulu', icon: '🫒', season: 'Sep–Oct' },
  { key: 'mulberry', cat: 'fruit', name: 'Mulberry', local: 'Toot', icon: '🍇', season: 'Jun–Jul' },
  { key: 'grape', cat: 'fruit', name: 'Grapes', local: 'Angoor', icon: '🍇', season: 'Aug–Sep' },
  { key: 'blackcurrant', cat: 'fruit', name: 'Black currant', local: 'Currant', icon: '🫐', season: 'Aug–Sep' },
  { key: 'strawberry', cat: 'fruit', name: 'Strawberry', local: 'Strawberry', icon: '🍓', season: 'Jun–Aug' },
  { key: 'melon', cat: 'fruit', name: 'Melon / watermelon', local: 'Kharbooza', icon: '🍈', season: 'Aug–Sep' },
  { key: 'pear', cat: 'fruit', name: 'Pear', local: 'Nashpati', icon: '🍐', season: 'Aug–Sep' },

  // --- Grain & flour --------------------------------------------------------
  { key: 'barley', cat: 'grain', name: 'Naked barley', local: 'Nas / Grim', icon: '🌾', season: 'Sep–Oct' },
  { key: 'tsampa', cat: 'grain', name: 'Roasted barley flour', local: 'Ngamphey / Tsampa', icon: '🌾', season: 'All year' },
  { key: 'wheat', cat: 'grain', name: 'Wheat', local: 'Tro', icon: '🌾', season: 'Sep–Oct' },
  { key: 'wheatflour', cat: 'grain', name: 'Wheat flour', local: 'Tro-phey', icon: '🌾', season: 'All year' },
  { key: 'buckwheat', cat: 'grain', name: 'Buckwheat', local: 'Trumba / Bro', icon: '🌾', season: 'Sep–Oct' },
  { key: 'peas_dry', cat: 'grain', name: 'Dry peas', local: 'Sran-ma kampo', icon: '🫛', season: 'Sep–Oct' },
  { key: 'quinoa', cat: 'grain', name: 'Quinoa', local: 'Quinoa', icon: '🌾', season: 'Sep–Oct' },
  { key: 'amaranth', cat: 'grain', name: 'Amaranth', local: 'Chua / Ramdana', icon: '🌾', season: 'Sep–Oct' },
  { key: 'mustardoil', cat: 'grain', name: 'Mustard / mustard oil', local: 'Yungkar', icon: '🌻', season: 'Sep–Nov' },

  // --- Seeds & saplings -----------------------------------------------------
  { key: 'seed_veg', cat: 'seed', name: 'Vegetable seed', local: 'Tsod-ma sa-bön', icon: '🌱', season: 'All year' },
  { key: 'seed_grain', cat: 'seed', name: 'Grain seed', local: 'Dru sa-bön', icon: '🌱', season: 'Feb–May' },
  { key: 'seed_potato', cat: 'seed', name: 'Seed potato', local: 'Aalu sa-bön', icon: '🥔', season: 'Mar–May' },
  { key: 'sapling_fruit', cat: 'seed', name: 'Fruit sapling', local: 'Shing-tog myu-gu', icon: '🌳', season: 'Mar–Apr, Oct–Nov' },
  { key: 'sapling_tree', cat: 'seed', name: 'Willow / poplar sapling', local: 'Chang-ma / Yarpa', icon: '🌳', season: 'Mar–Apr' },
  { key: 'seedling', cat: 'seed', name: 'Vegetable seedling', local: 'Myu-gu', icon: '🌿', season: 'Apr–Jun' },
  { key: 'compost', cat: 'seed', name: 'Compost / manure', local: 'Lud', icon: '🪱', season: 'All year' },

  // --- Dairy ----------------------------------------------------------------
  { key: 'butter', cat: 'dairy', name: 'Butter', local: 'Mar', icon: '🧈', season: 'All year' },
  { key: 'churpe', cat: 'dairy', name: 'Dried cheese', local: 'Churpe', icon: '🧀', season: 'All year' },
  { key: 'milk', cat: 'dairy', name: 'Milk', local: 'Oma', icon: '🥛', season: 'All year' },
  { key: 'curd', cat: 'dairy', name: 'Curd', local: 'Zho', icon: '🥣', season: 'All year' },
  { key: 'yakcheese', cat: 'dairy', name: 'Yak / dzo cheese', local: 'Yak churpe', icon: '🧀', season: 'All year' },

  // --- Dried & preserved ----------------------------------------------------
  { key: 'phating', cat: 'dry', name: 'Dried apricot', local: 'Phating', icon: '🍑', season: 'All year' },
  { key: 'kernel', cat: 'dry', name: 'Apricot kernel', local: 'Chuli giri', icon: '🌰', season: 'All year' },
  { key: 'apricotoil', cat: 'dry', name: 'Apricot kernel oil', local: 'Chuli mar-khu', icon: '🫗', season: 'All year' },
  { key: 'sbt_juice', cat: 'dry', name: 'Sea buckthorn juice', local: 'Tsestalulu khu-wa', icon: '🧃', season: 'All year' },
  { key: 'dryveg', cat: 'dry', name: 'Sun-dried vegetables', local: 'Tsod-ma kampo', icon: '🫙', season: 'Oct–Apr' },
  { key: 'honey', cat: 'dry', name: 'Local honey', local: 'Drangtsi', icon: '🍯', season: 'All year' },
  { key: 'herbs_dry', cat: 'dry', name: 'Dried herbs / tea', local: 'Men-tsa', icon: '🍵', season: 'All year' },

  // --- Other ----------------------------------------------------------------
  { key: 'fodder', cat: 'other', name: 'Fodder / alfalfa', local: 'Ol', icon: '🌿', season: 'Jun–Oct' },
  { key: 'wool', cat: 'other', name: 'Wool / Pashmina', local: 'Lena', icon: '🧶', season: 'May–Jun' },
  { key: 'basket', cat: 'other', name: 'Willow basket / craft', local: 'Tsepo', icon: '🧺', season: 'All year' },
  { key: 'other_item', cat: 'other', name: 'Something else', local: 'Zhan-dag', icon: '🧺', season: '—' },
];

// ---------------------------------------------------------------------------
// SEED BANK — the awareness engine.
// `status`: traditional | emerging | rare
//   traditional = grown here for centuries, sometimes being forgotten
//   emerging    = proven in Ladakh trials but few farmers grow it yet
//   rare        = high value, needs care or a long wait before it pays
// `sow` maps zone key -> sowing window. `harvest` likewise, keyed the same way.
// ---------------------------------------------------------------------------
export const SEEDS = [
  {
    key: 'quinoa',
    name: 'Quinoa',
    local: 'Quinoa',
    icon: '🌾',
    status: 'emerging',
    cropKey: 'quinoa',
    headline: 'A grain that likes cold, dry and salty ground — and sells for many times the price of barley.',
    why: 'Quinoa was bred in the high Andes, which is the closest thing on earth to Ladakh. It tolerates frost, needs very little water, does not mind poor or slightly salty soil, and has grown successfully up to about 4,000 m here. It carries far more protein than barley or wheat.',
    altMax: 4000,
    frost: 'Good — young plants survive light frost',
    days: '120–150 days',
    water: 'Low — roughly half of what wheat drinks',
    sow: { low: 'Late March – mid April', mid: 'Mid April – mid May', high: 'Mid May – early June', gh: 'Not needed — an open-field crop' },
    harvest: { low: 'August', mid: 'September', high: 'Late September', gh: '—' },
    yield: 'About 8–15 quintal per hectare',
    price: 'Sells far above barley — often ₹250–800/kg for clean, washed grain',
    care: 'Sow shallow, about 1–2 cm. Wash the grain after threshing to remove the bitter saponin coating, then dry it well. Birds love a ripening head, so net or watch the crop in the last two weeks.',
    source: 'DIHAR Leh, KVK Leh, Agriculture Department',
    tags: ['high protein', 'low water', 'high value'],
  },
  {
    key: 'seabuckthorn',
    name: 'Sea buckthorn',
    local: 'Tsestalulu / Tserman',
    icon: '🫒',
    status: 'emerging',
    cropKey: 'seabuckthorn',
    headline: 'It already grows wild along every stream in Ladakh. Planted in rows, it becomes an income.',
    why: 'Ladakh holds roughly seven-tenths of India\'s sea buckthorn. The berry is extraordinarily rich in vitamin C and the bush fixes nitrogen, binds riverbank soil and stops erosion. Most of it is still picked from the wild instead of being grown properly, so yields and quality stay low.',
    altMax: 4500,
    frost: 'Excellent — survives −40°C',
    days: 'Fruits from year 3–4, then for decades',
    water: 'Very low once established',
    sow: { low: 'Plant saplings March–April or October', mid: 'Plant saplings April or October', high: 'Plant saplings May', gh: 'Raise saplings under cover' },
    harvest: { low: 'September – October', mid: 'September – October', high: 'October', gh: '—' },
    yield: '5–15 kg of berry per mature bush',
    price: 'Fresh berry ₹60–150/kg; juice and pulp fetch far more',
    care: 'Plant one male bush for every six to eight females or you will get no fruit at all — this is the single most common mistake. Cut fruiting branches rather than stripping berries by hand; the thorns are serious.',
    source: 'Agriculture Department, DIHAR, local nurseries',
    tags: ['vitamin C', 'stops erosion', 'fixes nitrogen'],
  },
  {
    key: 'kale',
    name: 'Siberian kale',
    local: 'Kale',
    icon: '🥬',
    status: 'emerging',
    cropKey: 'kale',
    headline: 'Green leaves in January, from a trench greenhouse, when nothing else is growing.',
    why: 'Winter in Ladakh means months without fresh greens, and prices for anything green climb steeply. Siberian kale shrugs off hard frost and keeps producing leaf after leaf inside a trench greenhouse right through the deep cold. You cut the outer leaves and it grows more.',
    altMax: 4000,
    frost: 'Excellent — sweeter after frost',
    days: '55–70 days to first cut, then keeps giving',
    water: 'Moderate',
    sow: { low: 'August – September', mid: 'August – September', high: 'July – August', gh: 'September – October for winter cutting' },
    harvest: { low: 'October – December', mid: 'October – March under cover', high: 'September – November', gh: 'November – March' },
    yield: '2–4 kg per plant across a season',
    price: '₹80–200/kg in winter, when green vegetables are scarce',
    care: 'Sow into the trench by early October so the plants are established before the deep cold. Cut outer leaves only and leave the growing centre alone. Water sparingly in winter and only in the morning.',
    source: 'KVK Leh, Agriculture Department greenhouse scheme',
    tags: ['winter greens', 'greenhouse', 'cut and come again'],
  },
  {
    key: 'pakchoi',
    name: 'Pak choi',
    local: 'Pak choi',
    icon: '🥬',
    status: 'emerging',
    cropKey: 'pakchoi',
    headline: 'Ready in forty days. Two or three winter crops from the same trench.',
    why: 'Very few Ladakhi growers have tried pak choi, yet it is close to ideal for a trench greenhouse: it is fast, it likes cool weather, it does not mind low light, and hotels and restaurants in Leh buy every bunch they can find during the season.',
    altMax: 4000,
    frost: 'Good under cover',
    days: '40–55 days',
    water: 'Moderate — keep steady',
    sow: { low: 'September, then again in January', mid: 'September, then again in January', high: 'August', gh: 'September – February, sow every 3 weeks' },
    harvest: { low: 'October – November', mid: 'October – November', high: 'September – October', gh: 'October – April' },
    yield: '150–300 g per plant; a trench holds several hundred',
    price: '₹100–250/kg to hotels and restaurants',
    care: 'Sow a small patch every three weeks instead of everything at once, and you will have a steady supply rather than a glut. Harvest the whole head while it is still tight.',
    source: 'KVK Leh, private nurseries in Leh',
    tags: ['fast', 'greenhouse', 'restaurant demand'],
  },
  {
    key: 'chard',
    name: 'Swiss chard',
    local: 'Chard palak',
    icon: '🥬',
    status: 'emerging',
    cropKey: 'chard',
    headline: 'Sow once in autumn, cut leaves all winter long.',
    why: 'Chard is tougher than spinach and lasts much longer. One autumn sowing in a trench greenhouse can be harvested leaf by leaf from November all the way to April, which is exactly the window when Ladakh has no fresh greens and has to truck them up from Kashmir or Punjab.',
    altMax: 4000,
    frost: 'Very good under cover',
    days: '55 days to first cut, then continuous',
    water: 'Moderate',
    sow: { low: 'August – September', mid: 'August – September', high: 'July – August', gh: 'September – early October' },
    harvest: { low: 'October onward', mid: 'October – April under cover', high: 'September – October', gh: 'November – April' },
    yield: '60–90 kg per trench greenhouse over a winter',
    price: '₹80–180/kg in winter',
    care: 'Take the outermost leaves and always leave at least five at the centre. Do not let the leaves grow oversized — they get tough and the plant slows down.',
    source: 'KVK Leh, Agriculture Department',
    tags: ['winter greens', 'greenhouse', 'long harvest'],
  },
  {
    key: 'broccoli',
    name: 'Broccoli',
    local: 'Broccoli',
    icon: '🥦',
    status: 'emerging',
    cropKey: 'broccoli',
    headline: 'A cool-summer crop that does better in Leh than in the plains.',
    why: 'Broccoli hates heat, which is precisely why a Ladakhi summer suits it. It gives a big central head and then keeps producing smaller side shoots for weeks. Tourist-season hotels and Leh market pay well for it and very little is grown locally.',
    altMax: 3800,
    frost: 'Good — tolerates light frost',
    days: '80–100 days from transplant',
    water: 'Moderate to high',
    sow: { low: 'Nursery in March, transplant April', mid: 'Nursery in April, transplant late May', high: 'Nursery in May, transplant June', gh: 'Raise the nursery under cover a month early' },
    harvest: { low: 'July – September', mid: 'August – October', high: 'September', gh: '—' },
    yield: '300–600 g main head, plus side shoots',
    price: '₹100–250/kg',
    care: 'Raise the nursery under cover so you gain a month. Cut the central head while the buds are still tight and dark green — once it shows yellow flowers, the value is gone. Side shoots keep coming for a month after.',
    source: 'KVK Leh, Agriculture Department',
    tags: ['cool summer', 'hotel demand', 'keeps producing'],
  },
  {
    key: 'asparagus',
    name: 'Asparagus',
    local: 'Asparagus',
    icon: '🌿',
    status: 'rare',
    cropKey: 'seed_veg',
    headline: 'Plant it once. Harvest every spring for fifteen years.',
    why: 'Asparagus is a perennial that becomes fully hardy once established and is among the highest priced vegetables in India. It is also the first thing ready in spring, when nothing else is. Almost nobody in Ladakh grows it, and hotels currently fly it in.',
    altMax: 3600,
    frost: 'Excellent once established',
    days: 'First real harvest in year 3',
    water: 'Moderate',
    sow: { low: 'Plant crowns March – April', mid: 'Plant crowns April – May', high: 'Plant crowns May', gh: 'Raise crowns from seed under cover' },
    harvest: { low: 'April – May from year 3', mid: 'May – June from year 3', high: 'June from year 3', gh: '—' },
    yield: '3–5 kg per 10 m row once mature',
    price: '₹400–900/kg — one of the best returns per square metre',
    care: 'This is a patience crop. Do not cut a single spear in the first two years; let the ferns grow and feed the crown. Mulch heavily with manure each autumn. From year three it will pay you back every spring without replanting.',
    source: 'Order crowns through KVK or a nursery; not commonly stocked locally',
    tags: ['perennial', 'very high value', 'needs patience'],
  },
  {
    key: 'fodderbeet',
    name: 'Fodder beet',
    local: 'Fodder beet',
    icon: '🫒',
    status: 'emerging',
    cropKey: 'fodder',
    headline: 'The answer to the winter fodder gap — enormous roots that store till spring.',
    why: 'Winter feed is the hardest problem in Ladakhi livestock keeping, and families sell animals every autumn simply because they cannot feed them. Fodder beet yields several times more feed per field than alfalfa, and the roots keep in a cool store for months.',
    altMax: 3800,
    frost: 'Good — lift the roots before hard freeze',
    days: '150–180 days',
    water: 'Moderate',
    sow: { low: 'April', mid: 'Late April – May', high: 'Mid May', gh: 'Not needed' },
    harvest: { low: 'September – October', mid: 'October', high: 'Late September', gh: '—' },
    yield: '600–1,000 quintal per hectare of root — far above alfalfa',
    price: 'Mostly used at home; saves a great deal on bought feed',
    care: 'Space the plants well — they need room to swell. Lift the roots before the ground freezes hard and store them in a cool, dark room. Slice them before feeding so animals do not choke.',
    source: 'DIHAR Leh, Sheep Husbandry and Animal Husbandry departments',
    tags: ['winter fodder', 'huge yield', 'stores well'],
  },
  {
    key: 'buckwheat_bitter',
    name: 'Bitter buckwheat',
    local: 'Trumba / Bro',
    icon: '🌾',
    status: 'traditional',
    cropKey: 'buckwheat',
    headline: 'An old Ladakhi grain being forgotten, just as the outside world starts paying for it.',
    why: 'Bitter buckwheat ripens in about ninety days, which makes it the reliable crop in a short or late season, and it grows on thin soil that would not carry wheat. It carries a great deal of rutin and is naturally gluten-free — both things health food buyers now pay a premium for. Ladakhi households are steadily giving it up.',
    altMax: 4200,
    frost: 'Good — but the flowers are sensitive',
    days: '85–100 days',
    water: 'Low',
    sow: { low: 'May', mid: 'Late May – early June', high: 'June', gh: 'Not needed' },
    harvest: { low: 'August – September', mid: 'September', high: 'September – October', gh: '—' },
    yield: '6–12 quintal per hectare',
    price: '₹60–150/kg as grain; flour and noodles fetch far more',
    care: 'A good crop to sow after a failed or late-planted field, since it still has time to finish. Harvest when about three-quarters of the seed has turned brown — wait for all of it and the first-ripening seed drops to the ground.',
    source: 'Save your own seed; also KVK Leh and neighbours',
    tags: ['short season', 'gluten free', 'poor soil is fine'],
  },
  {
    key: 'amaranth',
    name: 'Amaranth',
    local: 'Chua / Ramdana',
    icon: '🌾',
    status: 'emerging',
    cropKey: 'amaranth',
    headline: 'Leaves for the kitchen in six weeks, grain for the market in four months.',
    why: 'Amaranth gives you two crops from one sowing: tender leaves early, then a heavy head of grain. It handles drought and heat swings well and the grain is high in protein and lysine, which cereals lack. It is barely grown in Ladakh despite fitting the season well.',
    altMax: 3500,
    frost: 'Poor — a frost-free window is essential',
    days: '100–130 days for grain, 40 for leaves',
    water: 'Low to moderate',
    sow: { low: 'April – May', mid: 'May', high: 'Marginal — try under cover first', gh: 'Start in April to gain a month' },
    harvest: { low: 'August – September', mid: 'September', high: '—', gh: '—' },
    yield: '8–15 quintal per hectare of grain',
    price: '₹120–300/kg',
    care: 'The seed is tiny — sow it shallow and press it into the surface rather than burying it. Cut the heads when the seed rubs free in your palm. It cannot take a hard frost, so in the high plateau treat it as an experiment before committing a field.',
    source: 'KVK Leh, DIHAR',
    tags: ['leaves and grain', 'high protein', 'drought tolerant'],
  },
  {
    key: 'garlic_local',
    name: 'Ladakhi garlic',
    local: 'Gogpa',
    icon: '🧄',
    status: 'traditional',
    cropKey: 'garlic',
    headline: 'Pungent, long-storing, and it holds its price straight through the winter.',
    why: 'Garlic grown at high altitude and under strong sun develops an unusually sharp flavour and strong pungency. It stores for months in an ordinary room, which means you are not forced to sell in the autumn glut — you can sell in February when the price is at its best.',
    altMax: 4000,
    frost: 'Excellent — cloves overwinter in the ground',
    days: '200–240 days if autumn planted',
    water: 'Low to moderate',
    sow: { low: 'October (best) or March', mid: 'October (best) or April', high: 'April – May', gh: 'Not needed' },
    harvest: { low: 'July – August', mid: 'August', high: 'September', gh: '—' },
    yield: '60–100 quintal per hectare',
    price: '₹150–400/kg, and highest late in winter',
    care: 'Autumn planting gives noticeably bigger bulbs than spring. Plant the largest cloves — small cloves make small bulbs. Stop watering two to three weeks before lifting, then cure the bulbs in shade with good airflow for a fortnight before storing.',
    source: 'Save your own bulbs; also local sellers here on Tsongra',
    tags: ['stores all winter', 'sell when prices peak', 'save your own seed'],
  },
  {
    key: 'turnip',
    name: 'Turnip',
    local: 'Nyungma',
    icon: '🥬',
    status: 'traditional',
    cropKey: 'turnip',
    headline: 'The crop that carried Ladakh through winter. Worth keeping.',
    why: 'Turnip is one of the most reliable things you can plant in Ladakh: it survives cold that kills most vegetables, the root feeds the family and the leaves feed the animals, and it stores through the winter. Households are drifting away from it, which quietly weakens their winter food security.',
    altMax: 4300,
    frost: 'Excellent — one of the hardiest crops here',
    days: '60–90 days',
    water: 'Low to moderate',
    sow: { low: 'April, and again in July', mid: 'May, and again in July', high: 'June', gh: 'August for a winter crop' },
    harvest: { low: 'July, and October', mid: 'August, and October', high: 'September', gh: 'November – January' },
    yield: '150–250 quintal per hectare',
    price: '₹20–60/kg',
    care: 'A second sowing in July gives a tender autumn crop for storage. Do not leave the roots to grow oversized — they turn woody. The leaves are excellent fodder, so nothing is wasted.',
    source: 'Save your own seed; also KVK Leh',
    tags: ['very hardy', 'food and fodder', 'stores well'],
  },
  {
    key: 'barley_naked',
    name: 'Naked barley',
    local: 'Nas / Grim',
    icon: '🌾',
    status: 'traditional',
    cropKey: 'barley',
    headline: 'Ladakh\'s own grain. Nothing else ripens so reliably this high.',
    why: 'Naked barley is the backbone of Ladakhi farming and the source of ngamphey. It threshes free of its husk, so it needs no milling machinery, and it will ripen at altitudes where wheat simply runs out of season. It is also the safest crop in a bad year.',
    altMax: 4300,
    frost: 'Excellent',
    days: '100–140 days depending on altitude',
    water: 'Moderate',
    sow: { low: 'Late March – April', mid: 'April – early May', high: 'Mid May', gh: 'Not needed' },
    harvest: { low: 'August', mid: 'September', high: 'Late September – October', gh: '—' },
    yield: '15–25 quintal per hectare',
    price: '₹35–70/kg as grain; ngamphey flour fetches more',
    care: 'Keep your best-performing local seed rather than replacing it wholesale — village selections are adapted to your exact valley and altitude. Roasting and grinding it into ngamphey yourself roughly doubles what the same grain earns.',
    source: 'Save your own seed; Agriculture Department, KVK',
    tags: ['staple', 'most reliable', 'sell as flour for more'],
  },
  {
    key: 'alfalfa',
    name: 'Alfalfa',
    local: 'Ol',
    icon: '🌿',
    status: 'traditional',
    cropKey: 'fodder',
    headline: 'Sow it once, cut it four times a year, for seven years.',
    why: 'Alfalfa is a perennial legume that pulls nitrogen out of the air and puts it into your soil, so the field improves each year instead of wearing out. It gives several cuts a season and its deep roots reach water that shallow-rooted crops cannot.',
    altMax: 4000,
    frost: 'Excellent',
    days: 'First cut in year 1; full yield from year 2',
    water: 'Moderate',
    sow: { low: 'April', mid: 'Late April – May', high: 'May – June', gh: 'Not needed' },
    harvest: { low: '3–4 cuts, June – September', mid: '3 cuts, June – September', high: '2 cuts, July – September', gh: '—' },
    yield: '60–100 quintal per hectare of dry fodder each year',
    price: '₹15–30/kg dried',
    care: 'Cut at first flowering — that is when leaf and protein peak. Take the last cut at least a month before the first hard frost so the crown can build reserves for winter, or the stand will thin out.',
    source: 'Agriculture Department, local seed',
    tags: ['perennial', 'feeds the soil', 'many cuts'],
  },
  {
    key: 'seedpotato',
    name: 'Seed potato',
    local: 'Aalu sa-bön',
    icon: '🥔',
    status: 'emerging',
    cropKey: 'seed_potato',
    headline: 'Ladakh\'s altitude keeps potato viruses away — that makes seed potato worth more than eating potato.',
    why: 'Aphids spread the viruses that ruin potato seed, and there are very few aphids this high and this dry. Potatoes grown in Ladakh therefore stay clean and make excellent seed, which sells for considerably more than ordinary table potato. Very few growers here realise their crop could be sold this way.',
    altMax: 4000,
    frost: 'Moderate — the plant tops are frost sensitive',
    days: '90–120 days',
    water: 'Moderate',
    sow: { low: 'April', mid: 'Late April – May', high: 'Mid May', gh: 'Not needed' },
    harvest: { low: 'August', mid: 'September', high: 'September', gh: '—' },
    yield: '200–350 quintal per hectare',
    price: 'Table ₹20–40/kg; certified seed potato well above that',
    care: 'Walk the field and pull out any plant with curled, mottled or stunted leaves before it can infect neighbours — this one habit is most of what separates seed-grade from table-grade. Store the tubers cool, dark and dry, and ask the Agriculture Department about certification.',
    source: 'Agriculture Department, KVK Leh',
    tags: ['high altitude advantage', 'worth more as seed', 'certification available'],
  },
  {
    key: 'cherrytomato',
    name: 'Cherry tomato',
    local: 'Cherry tamatar',
    icon: '🍅',
    status: 'emerging',
    cropKey: 'tomato',
    headline: 'A greenhouse crop timed for the tourist season, when Leh will pay almost anything for it.',
    why: 'From June to September, Leh\'s hotels, cafés and homestays need salad vegetables and almost all of it comes up the highway from outside. Cherry tomatoes ripen faster and more reliably in a greenhouse than large tomatoes, they crack less, and they carry a much better price.',
    altMax: 3800,
    frost: 'Poor — greenhouse only',
    days: '70–90 days from transplant',
    water: 'Moderate, steady',
    sow: { low: 'Nursery February, transplant April', mid: 'Nursery March, transplant May', high: 'Nursery March, transplant late May', gh: 'Nursery February – March' },
    harvest: { low: 'June – September', mid: 'July – September', high: 'August – September', gh: 'June – October' },
    yield: '2–4 kg per plant under cover',
    price: '₹150–350/kg during the season',
    care: 'Start the nursery inside in February or March so plants are ready the moment the greenhouse warms. Train them up a string and pinch out side shoots. Open the greenhouse for a few hours on warm days or the flowers will drop instead of setting fruit.',
    source: 'KVK Leh, Agriculture Department greenhouse scheme',
    tags: ['tourist season', 'greenhouse', 'high value'],
  },
  {
    key: 'strawberry',
    name: 'Strawberry',
    local: 'Strawberry',
    icon: '🍓',
    status: 'rare',
    cropKey: 'strawberry',
    headline: 'High price, small space, and Ladakh\'s cool nights make it taste better.',
    why: 'Strawberries develop more sugar and aroma where nights are cold, which is exactly the Ladakhi summer. The plants are perennial, they spread themselves through runners so you seldom buy plants twice, and a small tunnel can supply cafés in Leh throughout the season.',
    altMax: 3600,
    frost: 'Good with a straw or mulch cover in winter',
    days: 'Fruits in the second season',
    water: 'Moderate, steady',
    sow: { low: 'Plant runners March – April or September', mid: 'Plant runners April or September', high: 'Plant runners May', gh: 'Any time under cover' },
    harvest: { low: 'June – July', mid: 'June – August', high: 'July – August', gh: 'May – September' },
    yield: '250–500 g per plant per season',
    price: '₹300–700/kg',
    care: 'Mulch under the fruit so it never touches wet soil. Peg down the runners to make free new plants, and replace the mother plants every three years. Cover the crowns with straw before winter.',
    source: 'Nurseries in Leh, KVK',
    tags: ['very high value', 'small space', 'free new plants'],
  },
  {
    key: 'blackcurrant',
    name: 'Black currant',
    local: 'Currant',
    icon: '🫐',
    status: 'emerging',
    cropKey: 'blackcurrant',
    headline: 'A hardy bush that fruits for twenty years and makes excellent jam and juice.',
    why: 'Black currant is bred for cold northern climates and takes Ladakhi winters without protection. It fruits from the third year and keeps going for two decades, and processed into jam, squash or juice it earns several times the fresh berry price.',
    altMax: 3800,
    frost: 'Excellent',
    days: 'Fruits from year 3',
    water: 'Moderate',
    sow: { low: 'Plant cuttings March or October', mid: 'Plant cuttings April or October', high: 'Plant cuttings May', gh: 'Root cuttings under cover' },
    harvest: { low: 'July – August', mid: 'August', high: 'August – September', gh: '—' },
    yield: '2–4 kg per mature bush',
    price: 'Fresh ₹150–350/kg; jam and juice far above that',
    care: 'Cut out the oldest third of the branches each winter — fruit comes on younger wood. Take hardwood cuttings in autumn and you will never need to buy a bush again.',
    source: 'Horticulture Department, nurseries in Leh and Kargil',
    tags: ['very hardy', 'long lived', 'good for processing'],
  },
  {
    key: 'hops',
    name: 'Hops',
    local: 'Hops',
    icon: '🌿',
    status: 'rare',
    cropKey: 'other_item',
    headline: 'A climbing perennial with a small but well-paying market.',
    why: 'Hops are perennial, hardy, need a long summer day, and the Ladakhi summer gives exactly that. Craft breweries in India import almost all their hops. Volumes are small and you will need a buyer lined up before planting — but the price per kilo is high and almost nobody here grows it.',
    altMax: 3500,
    frost: 'Excellent — the root crown overwinters',
    days: 'First real crop in year 2–3',
    water: 'Moderate to high',
    sow: { low: 'Plant rhizomes March – April', mid: 'Plant rhizomes April', high: 'Marginal', gh: 'Not needed' },
    harvest: { low: 'August – September', mid: 'September', high: '—', gh: '—' },
    yield: '0.5–2 kg dried cones per mature plant',
    price: 'High, but it depends entirely on having a buyer',
    care: 'Hops climb five metres or more, so build strong tall supports before you plant. Dry the cones quickly in shade and pack them airtight. Find and confirm your buyer first — this is a contract crop, not a market crop.',
    source: 'Specialist suppliers; talk to KVK before committing land',
    tags: ['niche', 'needs a buyer first', 'perennial'],
  },
  {
    key: 'rhodiola',
    name: 'Rhodiola',
    local: 'Solo / Shrolo',
    icon: '🌸',
    status: 'rare',
    cropKey: 'other_item',
    headline: 'A high-value medicinal herb of the high plateau — but harvest it wild and you destroy it.',
    why: 'Rhodiola grows above 3,500 m, which rules out almost everywhere else in India, and the root is valuable to the herbal and pharmaceutical trade. Wild digging has already damaged the natural stands badly. Cultivating it is the way to earn from it without wiping it out.',
    altMax: 5000,
    frost: 'Excellent — it is a true alpine',
    days: 'Roots ready in year 4–5',
    water: 'Low',
    sow: { low: 'Not suited — too warm', mid: 'Sow April – May in a nursery', high: 'Sow May – June in a nursery', gh: 'Raise seedlings under cover, then plant out' },
    harvest: { low: '—', mid: 'September, from year 4', high: 'September, from year 4', gh: '—' },
    yield: '150–400 g of dry root per plant',
    price: 'Very high, but the trade is regulated',
    care: 'Grow it from nursery-raised seedlings, never by lifting wild plants. It is slow — plan on four to five years before the roots are worth harvesting. Check the current rules with the Forest and Agriculture Departments before selling, as collection and trade are controlled.',
    source: 'DIHAR Leh — talk to them before you start',
    tags: ['high altitude only', 'grow it, don\'t dig it', 'slow but valuable'],
  },
  {
    key: 'broadbean',
    name: 'Broad bean',
    local: 'Bakla',
    icon: '🫘',
    status: 'traditional',
    cropKey: 'broadbean',
    headline: 'Protein for the family and free nitrogen for next year\'s barley.',
    why: 'Broad bean is an old Ladakhi crop that tolerates cold better than almost any other pulse and can go into the ground very early. Being a legume, it leaves the soil richer than it found it, which makes it an excellent crop to rotate before barley or wheat.',
    altMax: 4000,
    frost: 'Very good — sow early',
    days: '110–130 days',
    water: 'Moderate',
    sow: { low: 'March', mid: 'April', high: 'May', gh: 'Not needed' },
    harvest: { low: 'July – August', mid: 'August', high: 'September', gh: '—' },
    yield: '12–20 quintal per hectare dry',
    price: '₹60–120/kg dry; green pods fetch more',
    care: 'Sow as early as the ground can be worked — it handles the cold. Pinch out the growing tip once pods have set to push the plant\'s energy into filling them. Leave the roots in the ground after harvest so the nitrogen stays in your field.',
    source: 'Save your own seed; KVK Leh',
    tags: ['feeds the soil', 'sow very early', 'good rotation crop'],
  },
  {
    key: 'kohlrabi',
    name: 'Kohlrabi',
    local: 'Ganth gobi',
    icon: '🥬',
    status: 'traditional',
    cropKey: 'kohlrabi',
    headline: 'Fast, hardy, and it will make a crop where cabbage runs out of time.',
    why: 'Kohlrabi is ready in around two months, which matters a great deal in a short season, and it takes frost well. Where a cabbage would not have time to form a head, kohlrabi will still give you a crop. It also stores for weeks in a cool room.',
    altMax: 4000,
    frost: 'Very good',
    days: '55–70 days',
    water: 'Moderate',
    sow: { low: 'April, and again July', mid: 'May, and again July', high: 'June', gh: 'August – September' },
    harvest: { low: 'June – September', mid: 'July – September', high: 'August – September', gh: 'October – December' },
    yield: '150–250 quintal per hectare',
    price: '₹30–70/kg',
    care: 'Harvest when the swollen stem is about the size of a tennis ball. Left longer it turns woody and stringy and buyers will notice. Sow twice in a season to spread the harvest.',
    source: 'KVK Leh, Agriculture Department',
    tags: ['fast', 'frost hardy', 'stores well'],
  },
  {
    key: 'lettuce',
    name: 'Lettuce & salad greens',
    local: 'Salad',
    icon: '🥗',
    status: 'emerging',
    cropKey: 'lettuce',
    headline: 'Six weeks from seed to sale, straight into the tourist season.',
    why: 'Lettuce and mixed salad leaves are among the fastest crops you can grow and hotels in Leh buy them constantly from June to September. Cool Ladakhi summers suit lettuce, which turns bitter and bolts in the heat of the plains.',
    altMax: 3800,
    frost: 'Moderate — good under cover',
    days: '40–60 days',
    water: 'Moderate, steady',
    sow: { low: 'April – July, every 2 weeks', mid: 'May – July, every 2 weeks', high: 'June', gh: 'September – March under cover' },
    harvest: { low: 'June – September', mid: 'June – September', high: 'August', gh: 'October – April' },
    yield: '200–400 g per head',
    price: '₹100–250/kg to hotels',
    care: 'Sow a small amount every two weeks rather than one big planting, or everything will be ready in the same week. Cut in the cool of the morning and get it to the buyer the same day — it wilts fast.',
    source: 'KVK Leh, nurseries in Leh',
    tags: ['very fast', 'hotel demand', 'sow in batches'],
  },
  {
    key: 'apricot_rk',
    name: 'Raktsey Karpo apricot',
    local: 'Raktsey Karpo',
    icon: '🍑',
    status: 'traditional',
    cropKey: 'apricot_rk',
    headline: 'Ladakh\'s first GI-tagged product. The white kernel exists nowhere else on earth.',
    why: 'Raktsey Karpo carries a Geographical Indication, which means only fruit actually grown in Ladakh may be sold under the name. It is exceptionally sweet and its white seed coat is unique to this region. That protected name is worth real money — provided the fruit is graded and dried properly rather than sold loose and mixed with ordinary apricot.',
    altMax: 3400,
    frost: 'Good for the tree — but spring flowers are at risk',
    days: 'Fruits from year 4–5',
    water: 'Moderate',
    sow: { low: 'Plant saplings March – April or October', mid: 'Plant saplings April or October', high: 'Marginal above 3,400 m', gh: 'Raise saplings under cover' },
    harvest: { low: 'July – August', mid: 'August', high: '—', gh: '—' },
    yield: '40–100 kg per mature tree',
    price: 'Fresh ₹80–200/kg; graded dried phating far above that',
    care: 'The great enemy is a late spring frost during flowering, so avoid low frost pockets when choosing where to plant. Dry the fruit on clean racks rather than on the ground and keep the variety separate from other apricots — mixing it destroys the price the GI name earns you.',
    source: 'Horticulture Department, registered nurseries',
    tags: ['GI protected', 'unique to Ladakh', 'grade it separately'],
  },
];

// ---------------------------------------------------------------------------
// Places. Ladakh was reorganised into seven districts (notified 27 April 2026).
// ---------------------------------------------------------------------------
export const DISTRICTS = [
  {
    key: 'leh', name: 'Leh', hq: 'Leh', zone: 'mid',
    villages: ['Leh town', 'Choglamsar', 'Shey', 'Thiksey', 'Chuchot', 'Stok', 'Matho', 'Spituk', 'Phyang', 'Saboo', 'Ranbirpur', 'Stakna', 'Kharu', 'Sakti', 'Chemrey', 'Igoo', 'Martselang', 'Upshi', 'Nimmoo', 'Taru'],
  },
  {
    key: 'sham', name: 'Sham', hq: 'Khaltse', zone: 'low',
    villages: ['Khaltse', 'Saspol', 'Basgo', 'Likir', 'Alchi', 'Uleytokpo', 'Domkhar', 'Skurbuchan', 'Achinathang', 'Dha', 'Hanu', 'Garkhon', 'Timosgang', 'Wanla', 'Lamayuru', 'Nurla', 'Hemis Shukpachan', 'Ang', 'Tia', 'Bema'],
  },
  {
    key: 'nubra', name: 'Nubra', hq: 'Diskit', zone: 'mid',
    villages: ['Diskit', 'Hunder', 'Sumur', 'Panamik', 'Turtuk', 'Bogdang', 'Tyakshi', 'Thang', 'Charasa', 'Tirit', 'Khardung', 'Khalsar', 'Tegar', 'Largyab', 'Skuru', 'Warshi', 'Chalunka', 'Udmaru', 'Kuri', 'Murgi'],
  },
  {
    key: 'changthang', name: 'Changthang', hq: 'Nyoma', zone: 'high',
    villages: ['Nyoma', 'Korzok', 'Chushul', 'Mahe', 'Loma', 'Hanle', 'Durbuk', 'Tangtse', 'Shachukul', 'Merak', 'Man', 'Spangmik', 'Kargyam', 'Anlay', 'Chumathang', 'Sumdo', 'Nidder', 'Rongo'],
  },
  {
    key: 'kargil', name: 'Kargil', hq: 'Kargil', zone: 'low',
    villages: ['Kargil town', 'Baroo', 'Poyen', 'Sankoo', 'Trespone', 'Karkitchoo', 'Panikhar', 'Parkachik', 'Shargole', 'Mulbekh', 'Chiktan', 'Bodhkharbu', 'Wakha', 'Silmoo', 'Thasgam', 'Hardass', 'Minji', 'Taisuru', 'Namsuru', 'Sanjak'],
  },
  {
    key: 'drass', name: 'Drass', hq: 'Drass', zone: 'high',
    villages: ['Drass town', 'Ranbirpura', 'Goshan', 'Murad Bagh', 'Bhimbet', 'Kaksar', 'Minamarg', 'Matayen', 'Pandrass', 'Shimsha Kharbu', 'Karkitchoo Drass', 'Tashgam', 'Holiyal', 'Lalung'],
  },
  {
    key: 'zanskar', name: 'Zanskar', hq: 'Padum', zone: 'high',
    villages: ['Padum', 'Karsha', 'Zangla', 'Sani', 'Stongde', 'Pipiting', 'Ating', 'Abring', 'Reru', 'Ichar', 'Cha', 'Raru', 'Testa', 'Shilingskit', 'Kargyak', 'Purne', 'Phe', 'Hanamur'],
  },
];

export const MARKETS = [
  { key: 'leh_main', name: 'Leh main market', district: 'leh' },
  { key: 'choglamsar', name: 'Choglamsar market', district: 'leh' },
  { key: 'kargil_main', name: 'Kargil main market', district: 'kargil' },
  { key: 'diskit', name: 'Diskit market', district: 'nubra' },
  { key: 'khaltse', name: 'Khaltse market', district: 'sham' },
  { key: 'padum', name: 'Padum market', district: 'zanskar' },
  { key: 'drass', name: 'Drass market', district: 'drass' },
  { key: 'nyoma', name: 'Nyoma market', district: 'changthang' },
];

export function districtZone(key) {
  return (DISTRICTS.find((d) => d.key === key) || {}).zone || 'mid';
}

export const CATALOGUE = { ZONES, CATEGORIES, UNITS, CROPS, SEEDS, DISTRICTS, MARKETS };
